name: Conventional Commits Pull Request
description: Lints a pull request title based on Conventional Commits
branding:
  icon: align-left
  color: blue
inputs:
  bots_ignore:
    required: false
    description: A list of bots to ignore when linting the pull request title. Can be a comma-separated list.
    default: ""
  comment:
    required: false
    description: Post a comment in the pull request conversation with examples.
    default: "true"
  token:
    required: false
    description: Access token to the repository. If not set, the action will use the default GitHub Actions token at runtime.
    default: ${{ github.token }}
  subject_pattern:
    required: false
    description: A regex pattern to validate the subject of the commit message.
    default: ""
runs:
  using: node20
  main: dist/index.js
