blank_issues_enabled: false
contact_links:
  - name: 💡 Have an idea for a new feature?
    url: https://github.com/jef/conventional-commits-pr-action/discussions
    about: Create a new idea discussion!
  - name: 🙇 Need help?
    url: https://github.com/jef/conventional-commits-pr-action/discussions
    about: Create a new help discussion if it hasn't been asked before!
